### ISSUE TITLE
[Android] Order of items ruined if menu has to scroll

### ISSUE THREAD

**Issue by danielang** [prscX/react-native-popover-menu#10] opened 2018-02-27 22:49 UTC
Hello @prscX 
I've found a strange bug on Android: If the menu has to scroll (in case the keyboard is displayed), the order of the icons which are not displayed gets messed up. See the attached [Video](https://drive.google.com/file/d/1Wlx_cpk9GRpxElUdS4gmKv26r0iG-wXf/view).  
Thank you!

**Comment by prscX** [comment] 2018-02-28 07:54
Thanks @danielang for raising the issue.

That's strange. I will create a similar sample app to test the same, or if possible can you please share your app landing page on Expo in order to test the same.

Thanks and Regards,
Pranav

**Comment by danielang** [comment] 2018-02-28 10:47
Hey @prscX 
I've created a short example of the screen you can take a look in the issues branch of my fork: [https://github.com/danielang/react-native-popover-menu/tree/issues](https://github.com/danielang/react-native-popover-menu/tree/issues)

**Comment by prscX** [comment] 2018-03-02 14:34
Thanks @danielang for sharing the example.

I have tested the same workflow but it is working as expected for me. Please find below screenshot of the same:

<img width="532" alt="screen shot 2018-03-02 at 8 02 06 pm" src="https://user-images.githubusercontent.com/28862892/36903757-a2aefb1a-1e54-11e8-9ae4-cce815d9b3b0.png">
<img width="535" alt="screen shot 2018-03-02 at 8 02 13 pm" src="https://user-images.githubusercontent.com/28862892/36903758-a2fa90f2-1e54-11e8-8d0e-812aa076eb83.png">

I have found one issue, when keyboard is visible and if we click on popover menu then the app was crashing because I was not calling show method from UI Thread.

Thanks
Pranav

**Comment by danielang** [comment] 2018-03-02 15:03
Hey @prscX,
It is very important that the list is bigger then your screen.
In my case the resolution is smaller than yours. So you have to increase the amount of items in the popover.

Thank you,
Daniel

**Comment by danielang** [comment] 2018-03-05 09:18
@prscX are you able to reproduce the bug?

**Comment by prscX** [comment] 2018-03-05 09:33
Yes @danielang, I am able to reproduce the issues, I have spent couple of hours, then I started looking to icons issue in production. Please give me some more time, I will definitely get back to you with results.

Thanks
Pranav

**Comment by prscX** [comment] 2018-03-18 16:32
Hi @danielang,

I have figured that this issue is related to native library [zawadz88/MaterialPopupMenu](https://github.com/zawadz88/MaterialPopupMenu). I have raised the same: [ISSUE: 14](https://github.com/zawadz88/MaterialPopupMenu/issues/14).

I will sync @zawadz88 and will keep you posted about the updates.

Thanks
Pranav

**Comment by prscX** [comment] 2018-03-19 06:00
Hi @danielang,

The issue is fixed by @zawadz88. Can you please install latest V0.0.9 and verify the same.

Let us know in case you still face the same issue.

Thanks
Pranav

**Closed** 2018-03-19 06:01 UTC
Labels: bug
