### ISSUE TITLE
positioning the pop-up in ios

### ISSUE THREAD

**Issue by rash6795** [prscX/react-native-popover-menu#36] opened 2019-02-26 10:33 UTC
![simulator screen shot - ipad pro 9 7-inch - 2019-02-26 at 15 56 15](https://user-images.githubusercontent.com/34880490/53406242-91e98000-39df-11e9-8b55-78fd2bacb88e.png)

**The button is in left of the view but the pop-over menu appears at the centre. Is there any way to give position so that it appears to left ?.  Or is there any configuration i missed in the code ?**

My code is as follows:

let menus = [ { label: "Options", menus: [{ label: 'Take a picture'},{ label: 'Photo Library'},{ label: 'Choose a document'}] } ]
RNPopoverMenu.Show(ref, {
	title: "",
	menus: menus, 
	roundedArrow: false, menuWidth: 200, rowHeight: 50, borderColor:'#979797',
	shadowColor: 'rgba(0,0,0,0.2)',shadowOpacity: 0.4,shadowRadius: 10,
	onDone: selection => { buttonActions(selection)},
	onCancel: () => { }
});

TIA

**Comment by rash6795** [comment] 2019-04-04 10:53
any hack-around or solution for this ????

**Comment by emannick** [comment] 2019-06-10 07:35
any solution for this?

**Comment by prscX** [comment] 2019-12-08 10:13
Thanks @rash6795 for raising issue.

I would recommend to add popover to label or inner view instead of root parent. It is showing expected behaviour since it take center of the view width.

Closing the issue since it is an expected behaviour.

Thanks
</ Pranav >

**Closed by prscX** 2019-12-08 10:13 UTC
